openapi: 3.0.0
info:
  version: 1.0.0
  title: Heroku-Salesforce API V2
  description: Sample Heroku app exposing APIs to connected Salesforce and Data Cloud orgs.
paths:
  /calculateLAERTotalfields:
    post:
      summary: Calculate LAER Total Fields
      operationId: calculateLAERTotalfields
      x-sfdc:
        heroku:
          authorization:
            connectedApp: HerokuLaerConnectedApp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - recId
                - sobjectType
              properties:
                recId:
                  type: string
                closeDate:
                  type: string
                  format: date
                sobjectType:
                  type: string
                  enum: [opportunity, contract]
                dealId:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object

            
  /accounts:
    get:
      tags:
        - accounts
      summary: Get All Accounts
      operationId: GetAccounts
      description: Returns array of Accounts
      x-sfdc:
        heroku:
          authorization:
            connectedApp: 'HerokuLaerModuleConnectedApp'
      responses:
        '200':
          description: Successfully returned a list of Accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
components:
  schemas:
    Account:
      type: object
      additionalProperties: true